/* The following code was generated by JFlex 1.5.0-SNAPSHOT */

/*----------------------------------------------------------------------------
--------------Analisis Lexico Practica1_201314810-------------------
----------------------------------------------------------------------------*/

//-------------------> Importaciones 
//-------------------> Paquetes 
//package Tools;
import java_cup.runtime.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.5.0-SNAPSHOT
 * from the specification file <tt>src/Lexico.jflex</tt>
 */
public class Lexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int CONTRA_ID = 2;
  public static final int DECIDIR = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\63\1\3\1\4\1\3\1\3\22\0\1\63\1\0\1\5"+
    "\1\11\1\7\1\10\2\0\1\31\1\32\1\16\1\15\1\13\1\1"+
    "\1\34\1\17\1\2\1\62\10\2\1\0\1\14\1\0\1\12\2\0"+
    "\1\33\2\6\1\52\5\6\1\41\4\6\1\61\1\6\1\20\1\6"+
    "\1\23\2\6\1\45\5\6\1\27\1\0\1\30\3\0\1\46\1\54"+
    "\1\43\1\47\1\36\1\56\1\57\1\6\1\42\2\6\1\55\1\53"+
    "\1\22\1\44\1\50\1\24\1\35\1\40\1\21\1\37\1\6\1\51"+
    "\3\6\1\25\1\0\1\26\7\0\1\4\153\0\1\60\u1f36\0\1\4"+
    "\1\4\udfd6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\3\1\4\1\1\1\5\1\6"+
    "\2\1\1\7\1\10\1\11\1\12\1\13\1\14\4\5"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\14\5\1\25\2\0\1\26\1\27\1\30\1\31\5\5"+
    "\1\32\4\5\1\33\13\5\1\34\1\35\11\5\1\36"+
    "\1\5\1\37\12\5\1\40\2\5\1\41\20\5\1\42"+
    "\1\43\3\5\1\0\2\5\1\44\4\5\1\45\7\5"+
    "\1\46\1\5\1\47\1\50\1\51\3\5\1\52\1\53"+
    "\10\5\1\54\11\5\1\55\1\56\1\5\1\57\1\60"+
    "\1\5\1\61\1\5\1\62\2\5\1\63\6\5\1\64"+
    "\2\5\1\65\1\66";

  private static int [] zzUnpackAction() {
    int [] result = new int[186];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\64\0\150\0\234\0\320\0\150\0\u0104\0\u0138"+
    "\0\150\0\u016c\0\u01a0\0\u01d4\0\150\0\150\0\150\0\150"+
    "\0\150\0\u0208\0\u023c\0\u0270\0\u02a4\0\150\0\150\0\150"+
    "\0\150\0\150\0\150\0\150\0\150\0\u02d8\0\u030c\0\u0340"+
    "\0\u0374\0\u03a8\0\u03dc\0\u0410\0\u0444\0\u0478\0\u04ac\0\u04e0"+
    "\0\u0514\0\u0138\0\u0548\0\u0104\0\150\0\150\0\150\0\150"+
    "\0\u057c\0\u05b0\0\u05e4\0\u0618\0\u064c\0\u0138\0\u0680\0\u06b4"+
    "\0\u06e8\0\u071c\0\u0138\0\u0750\0\u0784\0\u07b8\0\u07ec\0\u0820"+
    "\0\u0854\0\u0888\0\u08bc\0\u08f0\0\u0924\0\u0958\0\u0548\0\u0138"+
    "\0\u098c\0\u09c0\0\u09f4\0\u0a28\0\u0a5c\0\u0a90\0\u0ac4\0\u0af8"+
    "\0\u0b2c\0\u0138\0\u0b60\0\u0b94\0\u0bc8\0\u0bfc\0\u0c30\0\u0c64"+
    "\0\u0c98\0\u0ccc\0\u0d00\0\u0d34\0\u0d68\0\u0d9c\0\u0138\0\u0dd0"+
    "\0\u0e04\0\u0138\0\u0e38\0\u0e6c\0\u0ea0\0\u0ed4\0\u0f08\0\u0f3c"+
    "\0\u0f70\0\u0fa4\0\u0fd8\0\u100c\0\u1040\0\u1074\0\u10a8\0\u10dc"+
    "\0\u1110\0\u1144\0\u0138\0\u0138\0\u1178\0\u11ac\0\u11e0\0\u1214"+
    "\0\u1248\0\u127c\0\u0138\0\u12b0\0\u12e4\0\u1318\0\u134c\0\u0138"+
    "\0\u1380\0\u13b4\0\u13e8\0\u141c\0\u1450\0\u1484\0\u14b8\0\u0138"+
    "\0\u14ec\0\u0138\0\150\0\u0138\0\u1520\0\u1554\0\u1588\0\u0138"+
    "\0\u0138\0\u15bc\0\u15f0\0\u1624\0\u1658\0\u168c\0\u16c0\0\u16f4"+
    "\0\u1728\0\u0138\0\u175c\0\u1790\0\u17c4\0\u17f8\0\u182c\0\u1860"+
    "\0\u1894\0\u18c8\0\u18fc\0\u0138\0\u0138\0\u1930\0\u0138\0\u0138"+
    "\0\u1964\0\u0138\0\u1998\0\u0138\0\u19cc\0\u1a00\0\u0138\0\u1a34"+
    "\0\u1a68\0\u1a9c\0\u1ad0\0\u1b04\0\u1b38\0\u0138\0\u1b6c\0\u1ba0"+
    "\0\u0138\0\u0138";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[186];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\1\0\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\10\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\36\1\37\1\10"+
    "\1\40\1\41\1\42\1\43\2\10\1\44\1\45\1\46"+
    "\1\10\1\47\1\50\3\10\1\51\1\3\1\52\1\5"+
    "\1\6\3\3\1\6\1\0\56\3\1\6\66\0\1\5"+
    "\57\0\1\5\1\0\2\53\1\5\2\0\55\53\1\5"+
    "\1\53\5\54\1\55\56\54\2\0\1\10\3\0\1\10"+
    "\11\0\5\10\10\0\23\10\1\0\2\10\11\0\1\56"+
    "\64\0\1\57\64\0\1\60\53\0\1\10\3\0\1\10"+
    "\11\0\1\10\1\61\3\10\10\0\23\10\1\0\2\10"+
    "\3\0\1\10\3\0\1\10\11\0\5\10\10\0\1\10"+
    "\1\62\3\10\1\63\3\10\1\64\11\10\1\0\2\10"+
    "\3\0\1\10\3\0\1\10\11\0\5\10\10\0\7\10"+
    "\1\65\13\10\1\0\2\10\3\0\1\10\3\0\1\10"+
    "\11\0\4\10\1\66\10\0\23\10\1\0\2\10\3\0"+
    "\1\10\3\0\1\10\11\0\5\10\10\0\1\10\1\67"+
    "\21\10\1\0\2\10\3\0\1\10\3\0\1\10\11\0"+
    "\5\10\10\0\16\10\1\70\4\10\1\0\2\10\3\0"+
    "\1\10\3\0\1\10\11\0\5\10\10\0\2\10\1\71"+
    "\20\10\1\0\2\10\3\0\1\10\3\0\1\10\11\0"+
    "\2\10\1\72\2\10\10\0\23\10\1\0\2\10\3\0"+
    "\1\10\3\0\1\10\11\0\5\10\10\0\12\10\1\73"+
    "\3\10\1\74\4\10\1\0\2\10\3\0\1\10\3\0"+
    "\1\10\11\0\5\10\10\0\7\10\1\75\1\10\1\76"+
    "\11\10\1\0\2\10\3\0\1\10\3\0\1\10\11\0"+
    "\5\10\10\0\13\10\1\77\7\10\1\0\2\10\3\0"+
    "\1\10\3\0\1\10\11\0\5\10\10\0\5\10\1\100"+
    "\15\10\1\0\2\10\3\0\1\10\3\0\1\10\11\0"+
    "\5\10\10\0\1\101\10\10\1\102\11\10\1\0\2\10"+
    "\3\0\1\10\3\0\1\10\11\0\5\10\10\0\1\103"+
    "\6\10\1\104\13\10\1\0\2\10\3\0\1\10\3\0"+
    "\1\10\11\0\5\10\10\0\11\10\1\105\11\10\1\0"+
    "\2\10\3\0\1\10\3\0\1\10\11\0\5\10\10\0"+
    "\1\10\1\106\21\10\1\0\2\10\3\0\1\107\57\0"+
    "\1\107\3\0\1\10\3\0\1\10\11\0\2\10\1\110"+
    "\2\10\10\0\23\10\1\0\2\10\3\0\1\10\3\0"+
    "\1\10\11\0\5\10\10\0\20\10\1\111\2\10\1\0"+
    "\2\10\3\0\1\10\3\0\1\10\11\0\5\10\10\0"+
    "\1\10\1\112\11\10\1\113\7\10\1\0\2\10\3\0"+
    "\1\10\3\0\1\10\11\0\5\10\10\0\16\10\1\114"+
    "\4\10\1\0\2\10\3\0\1\10\3\0\1\10\11\0"+
    "\5\10\10\0\16\10\1\115\4\10\1\0\2\10\3\0"+
    "\1\10\3\0\1\10\11\0\4\10\1\116\10\0\23\10"+
    "\1\0\2\10\3\0\1\10\3\0\1\10\11\0\5\10"+
    "\10\0\11\10\1\117\11\10\1\0\2\10\3\0\1\10"+
    "\3\0\1\10\11\0\5\10\10\0\6\10\1\120\14\10"+
    "\1\0\2\10\3\0\1\10\3\0\1\10\11\0\5\10"+
    "\10\0\5\10\1\121\15\10\1\0\2\10\3\0\1\10"+
    "\3\0\1\10\11\0\5\10\10\0\22\10\1\122\1\0"+
    "\2\10\3\0\1\10\3\0\1\10\11\0\5\10\10\0"+
    "\12\10\1\123\3\10\1\124\1\10\1\125\2\10\1\0"+
    "\2\10\3\0\1\10\3\0\1\10\11\0\2\10\1\126"+
    "\2\10\10\0\23\10\1\0\2\10\3\0\1\10\3\0"+
    "\1\10\11\0\5\10\10\0\1\10\1\127\21\10\1\0"+
    "\2\10\3\0\1\10\3\0\1\10\11\0\5\10\10\0"+
    "\1\130\22\10\1\0\2\10\3\0\1\10\3\0\1\10"+
    "\11\0\5\10\10\0\7\10\1\131\13\10\1\0\2\10"+
    "\3\0\1\10\3\0\1\10\11\0\5\10\10\0\3\10"+
    "\1\132\17\10\1\0\2\10\3\0\1\10\3\0\1\10"+
    "\11\0\5\10\10\0\1\10\1\133\21\10\1\0\2\10"+
    "\3\0\1\10\3\0\1\10\11\0\2\10\1\134\2\10"+
    "\10\0\23\10\1\0\2\10\3\0\1\10\3\0\1\10"+
    "\11\0\1\10\1\135\3\10\10\0\1\136\22\10\1\0"+
    "\2\10\3\0\1\10\3\0\1\10\11\0\1\10\1\137"+
    "\3\10\10\0\23\10\1\0\2\10\3\0\1\10\3\0"+
    "\1\10\11\0\5\10\10\0\1\10\1\140\21\10\1\0"+
    "\2\10\3\0\1\10\3\0\1\10\11\0\2\10\1\141"+
    "\2\10\10\0\23\10\1\0\2\10\3\0\1\10\3\0"+
    "\1\10\11\0\5\10\10\0\7\10\1\142\13\10\1\0"+
    "\2\10\3\0\1\10\3\0\1\10\11\0\5\10\10\0"+
    "\11\10\1\143\11\10\1\0\2\10\3\0\1\10\3\0"+
    "\1\10\11\0\5\10\10\0\17\10\1\144\3\10\1\0"+
    "\2\10\3\0\1\10\3\0\1\10\11\0\5\10\10\0"+
    "\2\10\1\145\20\10\1\0\2\10\3\0\1\10\3\0"+
    "\1\10\11\0\5\10\10\0\5\10\1\146\15\10\1\0"+
    "\2\10\3\0\1\10\3\0\1\10\11\0\5\10\10\0"+
    "\2\10\1\147\20\10\1\0\2\10\3\0\1\10\3\0"+
    "\1\10\11\0\5\10\10\0\6\10\1\150\14\10\1\0"+
    "\2\10\3\0\1\10\3\0\1\10\11\0\5\10\10\0"+
    "\5\10\1\151\15\10\1\0\2\10\3\0\1\10\3\0"+
    "\1\10\11\0\5\10\10\0\13\10\1\152\7\10\1\0"+
    "\2\10\3\0\1\10\3\0\1\10\11\0\5\10\10\0"+
    "\7\10\1\153\13\10\1\0\2\10\3\0\1\10\3\0"+
    "\1\10\11\0\1\10\1\154\3\10\10\0\23\10\1\0"+
    "\2\10\3\0\1\10\3\0\1\10\11\0\5\10\10\0"+
    "\20\10\1\155\2\10\1\0\2\10\3\0\1\10\3\0"+
    "\1\10\11\0\5\10\10\0\1\10\1\156\21\10\1\0"+
    "\2\10\3\0\1\10\3\0\1\10\11\0\5\10\10\0"+
    "\12\10\1\157\1\160\7\10\1\0\2\10\3\0\1\10"+
    "\3\0\1\10\11\0\5\10\10\0\3\10\1\161\17\10"+
    "\1\0\2\10\3\0\1\10\3\0\1\10\11\0\5\10"+
    "\10\0\11\10\1\162\11\10\1\0\2\10\3\0\1\10"+
    "\3\0\1\10\11\0\5\10\10\0\3\10\1\163\17\10"+
    "\1\0\2\10\3\0\1\10\3\0\1\10\11\0\5\10"+
    "\10\0\1\10\1\164\21\10\1\0\2\10\3\0\1\10"+
    "\3\0\1\10\11\0\5\10\10\0\6\10\1\165\14\10"+
    "\1\0\2\10\3\0\1\10\3\0\1\10\11\0\5\10"+
    "\10\0\21\10\1\166\1\10\1\0\2\10\3\0\1\10"+
    "\3\0\1\10\11\0\5\10\10\0\12\10\1\167\10\10"+
    "\1\0\2\10\3\0\1\10\3\0\1\10\11\0\5\10"+
    "\10\0\23\10\1\170\2\10\3\0\1\10\3\0\1\10"+
    "\11\0\5\10\10\0\1\171\22\10\1\0\2\10\3\0"+
    "\1\10\3\0\1\10\11\0\5\10\10\0\1\10\1\172"+
    "\21\10\1\0\2\10\3\0\1\10\3\0\1\10\11\0"+
    "\5\10\10\0\20\10\1\173\2\10\1\0\2\10\3\0"+
    "\1\10\3\0\1\10\11\0\5\10\10\0\1\174\22\10"+
    "\1\0\2\10\3\0\1\10\3\0\1\10\11\0\5\10"+
    "\10\0\5\10\1\175\15\10\1\0\2\10\3\0\1\10"+
    "\3\0\1\10\11\0\5\10\10\0\22\10\1\176\1\0"+
    "\2\10\3\0\1\10\3\0\1\10\11\0\5\10\10\0"+
    "\5\10\1\177\15\10\1\0\2\10\3\0\1\10\3\0"+
    "\1\10\11\0\5\10\10\0\1\200\22\10\1\0\2\10"+
    "\3\0\1\10\3\0\1\10\11\0\5\10\10\0\5\10"+
    "\1\201\15\10\1\0\2\10\3\0\1\10\3\0\1\10"+
    "\11\0\5\10\10\0\20\10\1\202\2\10\1\0\2\10"+
    "\3\0\1\10\3\0\1\10\11\0\5\10\10\0\6\10"+
    "\1\203\14\10\1\0\2\10\3\0\1\10\3\0\1\10"+
    "\11\0\5\10\10\0\2\10\1\204\20\10\1\0\2\10"+
    "\3\0\1\10\3\0\1\10\11\0\5\10\10\0\5\10"+
    "\1\205\15\10\1\0\2\10\3\0\1\10\3\0\1\10"+
    "\11\0\5\10\10\0\14\10\1\206\6\10\1\0\2\10"+
    "\3\0\1\10\3\0\1\10\11\0\5\10\10\0\1\207"+
    "\22\10\1\0\2\10\3\0\1\10\3\0\1\10\11\0"+
    "\5\10\10\0\11\10\1\210\11\10\1\0\2\10\3\0"+
    "\1\10\3\0\1\10\11\0\5\10\10\0\7\10\1\211"+
    "\13\10\1\0\2\10\3\0\1\10\3\0\1\10\11\0"+
    "\5\10\10\0\11\10\1\212\11\10\1\0\2\10\45\0"+
    "\1\213\21\0\1\10\3\0\1\10\11\0\5\10\10\0"+
    "\1\10\1\214\21\10\1\0\2\10\3\0\1\10\3\0"+
    "\1\10\11\0\5\10\10\0\3\10\1\215\17\10\1\0"+
    "\2\10\3\0\1\10\3\0\1\10\11\0\5\10\10\0"+
    "\3\10\1\216\17\10\1\0\2\10\3\0\1\10\3\0"+
    "\1\10\11\0\5\10\10\0\7\10\1\217\13\10\1\0"+
    "\2\10\3\0\1\10\3\0\1\10\11\0\5\10\10\0"+
    "\7\10\1\220\13\10\1\0\2\10\3\0\1\10\3\0"+
    "\1\10\11\0\5\10\10\0\23\10\1\0\1\10\1\221"+
    "\3\0\1\10\3\0\1\10\11\0\5\10\10\0\12\10"+
    "\1\222\10\10\1\0\2\10\3\0\1\10\3\0\1\10"+
    "\11\0\5\10\10\0\5\10\1\223\15\10\1\0\2\10"+
    "\3\0\1\10\3\0\1\10\11\0\5\10\10\0\6\10"+
    "\1\224\14\10\1\0\2\10\3\0\1\10\3\0\1\10"+
    "\11\0\5\10\10\0\6\10\1\225\14\10\1\0\2\10"+
    "\3\0\1\10\3\0\1\10\11\0\5\10\10\0\1\10"+
    "\1\226\21\10\1\0\2\10\3\0\1\10\3\0\1\10"+
    "\11\0\5\10\10\0\7\10\1\227\13\10\1\0\2\10"+
    "\3\0\1\10\3\0\1\10\11\0\5\10\10\0\10\10"+
    "\1\230\12\10\1\0\2\10\3\0\1\10\3\0\1\10"+
    "\11\0\2\10\1\231\2\10\10\0\23\10\1\0\2\10"+
    "\3\0\1\10\3\0\1\10\11\0\1\10\1\232\3\10"+
    "\10\0\23\10\1\0\2\10\3\0\1\10\3\0\1\10"+
    "\11\0\5\10\10\0\11\10\1\233\11\10\1\0\2\10"+
    "\3\0\1\10\3\0\1\10\11\0\5\10\10\0\10\10"+
    "\1\234\12\10\1\0\2\10\3\0\1\10\3\0\1\10"+
    "\11\0\5\10\10\0\11\10\1\235\11\10\1\0\2\10"+
    "\3\0\1\10\3\0\1\10\11\0\5\10\10\0\12\10"+
    "\1\236\10\10\1\0\2\10\3\0\1\10\3\0\1\10"+
    "\11\0\5\10\10\0\5\10\1\237\15\10\1\0\2\10"+
    "\3\0\1\10\3\0\1\10\11\0\1\10\1\240\3\10"+
    "\10\0\23\10\1\0\2\10\3\0\1\10\3\0\1\10"+
    "\11\0\1\10\1\241\3\10\10\0\23\10\1\0\2\10"+
    "\3\0\1\10\3\0\1\10\11\0\5\10\10\0\1\242"+
    "\22\10\1\0\2\10\3\0\1\10\3\0\1\10\11\0"+
    "\5\10\10\0\3\10\1\243\17\10\1\0\2\10\3\0"+
    "\1\10\3\0\1\10\11\0\5\10\10\0\7\10\1\244"+
    "\13\10\1\0\2\10\3\0\1\10\3\0\1\10\11\0"+
    "\5\10\10\0\20\10\1\245\2\10\1\0\2\10\3\0"+
    "\1\10\3\0\1\10\11\0\5\10\10\0\3\10\1\246"+
    "\17\10\1\0\2\10\3\0\1\10\3\0\1\10\11\0"+
    "\5\10\10\0\12\10\1\247\10\10\1\0\2\10\3\0"+
    "\1\10\3\0\1\10\11\0\5\10\10\0\7\10\1\250"+
    "\13\10\1\0\2\10\3\0\1\10\3\0\1\10\11\0"+
    "\5\10\10\0\7\10\1\251\13\10\1\0\2\10\3\0"+
    "\1\10\3\0\1\10\11\0\5\10\10\0\7\10\1\252"+
    "\13\10\1\0\2\10\3\0\1\10\3\0\1\10\11\0"+
    "\5\10\10\0\11\10\1\253\11\10\1\0\2\10\3\0"+
    "\1\10\3\0\1\10\11\0\5\10\10\0\12\10\1\254"+
    "\10\10\1\0\2\10\3\0\1\10\3\0\1\10\11\0"+
    "\5\10\10\0\2\10\1\255\20\10\1\0\2\10\3\0"+
    "\1\10\3\0\1\10\11\0\5\10\10\0\2\10\1\256"+
    "\20\10\1\0\2\10\3\0\1\10\3\0\1\10\11\0"+
    "\2\10\1\257\2\10\10\0\23\10\1\0\2\10\3\0"+
    "\1\10\3\0\1\10\11\0\5\10\10\0\1\260\22\10"+
    "\1\0\2\10\3\0\1\10\3\0\1\10\11\0\5\10"+
    "\10\0\11\10\1\261\11\10\1\0\2\10\3\0\1\10"+
    "\3\0\1\10\11\0\5\10\10\0\11\10\1\262\11\10"+
    "\1\0\2\10\3\0\1\10\3\0\1\10\11\0\5\10"+
    "\10\0\5\10\1\263\15\10\1\0\2\10\3\0\1\10"+
    "\3\0\1\10\11\0\5\10\10\0\1\264\22\10\1\0"+
    "\2\10\3\0\1\10\3\0\1\10\11\0\5\10\10\0"+
    "\1\265\22\10\1\0\2\10\3\0\1\10\3\0\1\10"+
    "\11\0\5\10\10\0\7\10\1\266\13\10\1\0\2\10"+
    "\3\0\1\10\3\0\1\10\11\0\5\10\10\0\5\10"+
    "\1\267\15\10\1\0\2\10\3\0\1\10\3\0\1\10"+
    "\11\0\5\10\10\0\5\10\1\270\15\10\1\0\2\10"+
    "\3\0\1\10\3\0\1\10\11\0\5\10\10\0\7\10"+
    "\1\271\13\10\1\0\2\10\3\0\1\10\3\0\1\10"+
    "\11\0\5\10\10\0\7\10\1\272\13\10\1\0\2\10"+
    "\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7124];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\2\1\1\11\2\1\1\11\3\1\5\11"+
    "\4\1\10\11\15\1\2\0\4\11\107\1\1\0\22\1"+
    "\1\11\57\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[186];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    //-------------------> Codigo de usuario en sintaxis java


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexico(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexico(java.io.InputStream in) {
    this(new java.io.InputStreamReader
             (in, java.nio.charset.Charset.forName("UTF-8")));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 164) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

    // numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 1: 
          { System.out.println("Error Lexico: <<"+yytext()+">> Linea: "+yyline+" ,Columna: "+yycolumn);
          }
        case 55: break;
        case 2: 
          { return new Symbol(Simbolos.menos, yycolumn, yyline, yytext());
          }
        case 56: break;
        case 3: 
          { return new Symbol(Simbolos.numero, yycolumn, yyline, yytext());
          }
        case 57: break;
        case 4: 
          { /* Espacios en blanco, se ignoran */
          }
        case 58: break;
        case 5: 
          { return new Symbol(Simbolos.idd	, yycolumn, yyline, yytext());
          }
        case 59: break;
        case 6: 
          { return new Symbol(Simbolos.doll, yycolumn, yyline, yytext());
          }
        case 60: break;
        case 7: 
          { return new Symbol(Simbolos.igual, yycolumn, yyline, yytext());
          }
        case 61: break;
        case 8: 
          { return new Symbol(Simbolos.coma, yycolumn, yyline, yytext());
          }
        case 62: break;
        case 9: 
          { return new Symbol(Simbolos.pcoma, yycolumn, yyline, yytext());
          }
        case 63: break;
        case 10: 
          { return new Symbol(Simbolos.mas, yycolumn, yyline, yytext());
          }
        case 64: break;
        case 11: 
          { return new Symbol(Simbolos.por, yycolumn, yyline, yytext());
          }
        case 65: break;
        case 12: 
          { return new Symbol(Simbolos.dividir, yycolumn, yyline, yytext());
          }
        case 66: break;
        case 13: 
          { return new Symbol(Simbolos.allv, yycolumn, yyline, yytext());
          }
        case 67: break;
        case 14: 
          { return new Symbol(Simbolos.cllv, yycolumn, yyline, yytext());
          }
        case 68: break;
        case 15: 
          { return new Symbol(Simbolos.acor, yycolumn, yyline, yytext());
          }
        case 69: break;
        case 16: 
          { return new Symbol(Simbolos.ccor, yycolumn, yyline, yytext());
          }
        case 70: break;
        case 17: 
          { return new Symbol(Simbolos.apar, yycolumn, yyline, yytext());
          }
        case 71: break;
        case 18: 
          { return new Symbol(Simbolos.cpar, yycolumn, yyline, yytext());
          }
        case 72: break;
        case 19: 
          { return new Symbol(Simbolos.arr, yycolumn, yyline, yytext());
          }
        case 73: break;
        case 20: 
          { return new Symbol(Simbolos.pto, yycolumn, yyline, yytext());
          }
        case 74: break;
        case 21: 
          { return new Symbol(Simbolos.nott, yycolumn, yyline, yytext());
          }
        case 75: break;
        case 22: 
          { return new Symbol(Simbolos.cadena, yycolumn, yyline, yytext());
          }
        case 76: break;
        case 23: 
          { return new Symbol(Simbolos.andd, yycolumn, yyline, yytext());
          }
        case 77: break;
        case 24: 
          { return new Symbol(Simbolos.orr, yycolumn, yyline, yytext());
          }
        case 78: break;
        case 25: 
          { return new Symbol(Simbolos.igualdad, yycolumn, yyline, yytext());
          }
        case 79: break;
        case 26: 
          { return new Symbol(Simbolos.raiz, yycolumn, yyline, yytext());
          }
        case 80: break;
        case 27: 
          { return new Symbol(Simbolos.id, yycolumn, yyline, yytext());
          }
        case 81: break;
        case 28: 
          { return new Symbol(Simbolos.decimal, yycolumn, yyline, yytext());
          }
        case 82: break;
        case 29: 
          { return new Symbol(Simbolos.potencia, yycolumn, yyline, yytext());
          }
        case 83: break;
        case 30: 
          { return new Symbol(Simbolos.ig, yycolumn, yyline, yytext());
          }
        case 84: break;
        case 31: 
          { return new Symbol(Simbolos.cm, yycolumn, yyline, yytext());
          }
        case 85: break;
        case 32: 
          { return new Symbol(Simbolos.gt, yycolumn, yyline, yytext());
          }
        case 86: break;
        case 33: 
          { return new Symbol(Simbolos.to, yycolumn, yyline, yytext());
          }
        case 87: break;
        case 34: 
          { return new Symbol(Simbolos.cs, yycolumn, yyline, yytext());
          }
        case 88: break;
        case 35: 
          { return new Symbol(Simbolos.me, yycolumn, yyline, yytext());
          }
        case 89: break;
        case 36: 
          { return new Symbol(Simbolos.el, yycolumn, yyline, yytext());
          }
        case 90: break;
        case 37: 
          { return new Symbol(Simbolos.cr, yycolumn, yyline, yytext());
          }
        case 91: break;
        case 38: 
          { return new Symbol(Simbolos.ma, yycolumn, yyline, yytext());
          }
        case 92: break;
        case 39: 
          { return new Symbol(Simbolos.ta, yycolumn, yyline, yytext());
          }
        case 93: break;
        case 40: 
          { return new Symbol(Simbolos.tmo, yycolumn, yyline, yytext());
          }
        case 94: break;
        case 41: 
          { return new Symbol(Simbolos.ne, yycolumn, yyline, yytext());
          }
        case 95: break;
        case 42: 
          { return new Symbol(Simbolos.cod, yycolumn, yyline, yytext());
          }
        case 96: break;
        case 43: 
          { return new Symbol(Simbolos.c1, yycolumn, yyline, yytext());
          }
        case 97: break;
        case 44: 
          { return new Symbol(Simbolos.rt, yycolumn, yyline, yytext());
          }
        case 98: break;
        case 45: 
          { return new Symbol(Simbolos.tel, yycolumn, yyline, yytext());
          }
        case 99: break;
        case 46: 
          { return new Symbol(Simbolos.sl, yycolumn, yyline, yytext());
          }
        case 100: break;
        case 47: 
          { return new Symbol(Simbolos.cd, yycolumn, yyline, yytext());
          }
        case 101: break;
        case 48: 
          { return new Symbol(Simbolos.ao, yycolumn, yyline, yytext());
          }
        case 102: break;
        case 49: 
          { return new Symbol(Simbolos.pro, yycolumn, yyline, yytext());
          }
        case 103: break;
        case 50: 
          { return new Symbol(Simbolos.pd, yycolumn, yyline, yytext());
          }
        case 104: break;
        case 51: 
          { return new Symbol(Simbolos.dn, yycolumn, yyline, yytext());
          }
        case 105: break;
        case 52: 
          { return new Symbol(Simbolos.po, yycolumn, yyline, yytext());
          }
        case 106: break;
        case 53: 
          { return new Symbol(Simbolos.co, yycolumn, yyline, yytext());
          }
        case 107: break;
        case 54: 
          { return new Symbol(Simbolos.io, yycolumn, yyline, yytext());
          }
        case 108: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(Simbolos.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
