
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 14 12:37:42 CST 2016
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int pto = 33;
  public static final int raiz = 25;
  public static final int ne = 10;
  public static final int ta = 7;
  public static final int idd = 27;
  public static final int gt = 50;
  public static final int ao = 30;
  public static final int c1 = 31;
  public static final int dividir = 23;
  public static final int coma = 28;
  public static final int dn = 37;
  public static final int igual = 11;
  public static final int nott = 46;
  public static final int cod = 40;
  public static final int po = 39;
  public static final int sl = 42;
  public static final int igualdad = 48;
  public static final int arr = 36;
  public static final int me = 9;
  public static final int andd = 47;
  public static final int pd = 29;
  public static final int ma = 52;
  public static final int numero = 19;
  public static final int menos = 4;
  public static final int tel = 34;
  public static final int cs = 14;
  public static final int cr = 51;
  public static final int EOF = 0;
  public static final int mas = 22;
  public static final int co = 6;
  public static final int error = 1;
  public static final int cm = 32;
  public static final int pcoma = 21;
  public static final int io = 5;
  public static final int rt = 3;
  public static final int por = 26;
  public static final int cd = 43;
  public static final int ig = 41;
  public static final int cllv = 16;
  public static final int pro = 8;
  public static final int potencia = 24;
  public static final int id = 13;
  public static final int orr = 49;
  public static final int ccor = 45;
  public static final int doll = 2;
  public static final int cpar = 18;
  public static final int tmo = 53;
  public static final int allv = 15;
  public static final int el = 35;
  public static final int acor = 44;
  public static final int decimal = 20;
  public static final int to = 38;
  public static final int cadena = 12;
  public static final int apar = 17;
}

