
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Apr 02 10:59:50 CST 2016
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int pto = 36;
  public static final int raiz = 28;
  public static final int ne = 10;
  public static final int ta = 7;
  public static final int idd = 30;
  public static final int gt = 53;
  public static final int ao = 33;
  public static final int c1 = 34;
  public static final int dividir = 26;
  public static final int coma = 31;
  public static final int dn = 40;
  public static final int igual = 11;
  public static final int nott = 49;
  public static final int cod = 43;
  public static final int mn = 14;
  public static final int po = 42;
  public static final int sl = 45;
  public static final int igualdad = 51;
  public static final int arr = 39;
  public static final int me = 9;
  public static final int andd = 50;
  public static final int pd = 32;
  public static final int ma = 55;
  public static final int numero = 22;
  public static final int menos = 4;
  public static final int tel = 37;
  public static final int cs = 17;
  public static final int cr = 54;
  public static final int EOF = 0;
  public static final int mas = 25;
  public static final int co = 6;
  public static final int error = 1;
  public static final int cm = 35;
  public static final int pcoma = 24;
  public static final int io = 5;
  public static final int rt = 3;
  public static final int por = 29;
  public static final int cd = 46;
  public static final int ig = 44;
  public static final int cllv = 19;
  public static final int pro = 8;
  public static final int potencia = 27;
  public static final int id = 16;
  public static final int car = 13;
  public static final int orr = 52;
  public static final int ccor = 48;
  public static final int doll = 2;
  public static final int cpar = 21;
  public static final int tmo = 56;
  public static final int allv = 18;
  public static final int er = 15;
  public static final int el = 38;
  public static final int acor = 47;
  public static final int decimal = 23;
  public static final int to = 41;
  public static final int cadena = 12;
  public static final int apar = 20;
}

